model:
  mode: 'rgb'
  num_classes: 2000
  weights: './model/FINAL_nslt_2000_iters=5104_top1=32.48_top5=57.31_top10=66.31.pt'
  wlasl_class_list: './config/wlasl_class_list.txt'
  in_channels: 3
  hugging_face_k2t_token: "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"
  hugging_face_k2t_api : "https://api-inference.huggingface.co/models/beyond/genius-base"
  